### ISSUE TITLE
Question: may I please reserve a DeciderType ID?

### ISSUE THREAD

**Issue by UncombedCoconut** [TonyGuil/bbchallenge#1]
Hi!
I'm getting a powerful new decider ready for publication.
I'm interested in continuing the DVF tradition -- after all, why not?
So I've got my decider emitting this format (aside from accurate nEntries) and in internal testing I've used the ID of 5.
I have no particular attachment to the number 5, but would you be OK with the DVF doc reserving some ID for finite-automata proofs?
Thanks. :)

**Comment by UncombedCoconut** [comment]
I forgot that 5 was already used for Halting Segment (just not in the top-level readme) -- I'll at least increment past that.

**Comment by TonyGuil** [comment]
@UncombedCoconut: Perhaps you didn't get my email of 6th November. Anyway, here it is again:

> Hi Justin,
> 
> I've already been using 5 for Halting Segments, and 6 for Bouncers (to be announced soon!). And I might want to split Bouncers up into several cases. So take 10 if you like; or you might want to reserve a range, say 10-19, as finite-automata proofs sounds like a wide topic.
> 
> Have fun!

**Comment by UncombedCoconut** [comment]
Yeah, sorry, I didn't receive that, but I'll update my side to 10 now.
Thanks!
