### ISSUE TITLE
Compilers are annoying about BIG_ENDIAN

### ISSUE THREAD

**Issue by UncombedCoconut** [TonyGuil/bbchallenge#5]
On my environment, some standard header includes `<endian.h>` which always defines `BIG_ENDIAN` (in support of tests like `BYTE_ORDER == BIG_ENDIAN`), so the byte-swaps in `bbchallenge.h` are erroneously skipped.

Options include:
- `ntohl()` from `<arpa/inet.h>` (converts a big-endian `uint32_t` to host ordering)
- `boost::endian::big_to_native`
- `std::endian::native == std::endian::big` using `<bit>` from C++20 (may require a compiler flag like -std=c++20)
- Simply cast/`<<`/`|` the bytes and hope the optimizer fixes it.

Any of these sound particularly appealing?

**Comment by TonyGuil** [comment]
I have chosen the `boost::endian` option, and uploaded the results to GitHub.
