### ISSUE TITLE
Bouncers: off-by-4GB, "#1010841: Error at line 496 in CheckTapesEquivalent"

### ISSUE THREAD

**Issue by UncombedCoconut** [TonyGuil/bbchallenge#7]
Hi!
I'm trying to do two new things at once here.
1. Run the decider on a 64-bit system. I had enough trouble with targeted crash-fixes that I gave up and made it compile cleanly with `-Wsign-conversion` (which is a very noisy change): https://github.com/TonyGuil/bbchallenge/compare/main...UncombedCoconut:bbchallenge-tonyg:main
2. Run the decider on the full seed DB. (I'm doing this for many deciders to test their coverage systematically.)

It would be helpful to know if you can run this successfully on your 32-bit system:
`./DecideBouncers -X1010841 -T100000 -S5000`
If yes, I probably just introduced a bug.
If no, perhaps there's a corner-case bug provoked by this machine, which would normally have been filtered out by BackwardReasoning.

**Comment by TonyGuil** [comment]
I tried it, and it failed with "Error at line 503 in CheckTapesEquivalent". But it certainly looks like a Bouncer! Specifically, it looks like a Translated Bouncer with 1 partition and 12 runs, so it shouldn't cause problems. I must look into this.

**Comment by TonyGuil** [comment]
I have fixed and pushed the problem with #1010841. As for your 64-bit changes: that's just...horrible! I'm not going to make all those changes to my code. A simpler solution is to compile with `-m32`, for a 32-bit executable.

**Comment by UncombedCoconut** [comment]
Fortunately, if I know the CheckTapesEquivalent error wasn't my fault, I should have an easier time finding a clean fix at the source level.
That can be a separate PR.
If I'm successful, I'll urge its application: it's unclear that -m32 is a universal fix in the age of things like ARM-based Macs.
