### ISSUE TITLE
tiny typo

### ISSUE THREAD

**Issue by colette-b** [TonyGuil/bbchallenge#8]
https://github.com/TonyGuil/bbchallenge/blob/3cabab097685cf668cee5e59fe440c33a3af7962/FAR/FAR_Verifier.cpp#L221
used this for some debugging, I suppose it should have been 
```
printf ("(%d %d) ", DFA[i][0], DFA[i][1]) ;
```

**Comment by TonyGuil** [comment]
Thank you!
